#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	FilePath=$1
	IP=$2
	Username=$3
	SshKeyPath=$4
	scp -o StrictHostKeyChecking=no -i "$SshKeyPath" "$FilePath" "$Username"@"$IP":~/
fi
