#!/usr/bin/env bash
# Script thats install nginx web server
apt-get -y update
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
ufw allow 'Nginx HTTP'
tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

sudo service nginx restart
