#!/usr/bin/env bash
# Script thats fix nginx web server
sudo rm /etc/nginx/sites-enabled/default;
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default;
sudo service nginx restart